apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m
  path: ../../../../tenant-repo/apps/podinfo  # Path to your app inside tenant-repo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-tenant
  targetNamespace: default

