apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-tenant
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/JeevithaChandana/tenant-repo  # Replace with your tenant repo URL
  branch: main

