apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 1m
  path: ../../../../tenant-repo/apps/nginx  # Relative path to tenant-repo in your local setup
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-tenant
  targetNamespace: default

